export default function sitemap() {
  const baseUrl = "https://errordex.dev";

  const failures = [
    "gha-exit-137",
    "gha-exit-1-docker-buildx",
    "gitlab-docker-daemon-not-running",
    "gha-node-heap-exceeded",
    "gha-npm-ci-frozen-lockfile",
    "gha-actions-checkout-permission",
    "gha-docker-layer-cache-miss",
    "gha-jest-timeout",
    "gitlab-runner-no-space",
    "gha-env-secret-empty",
    "gha-python-pip-no-module",
    "gha-artifact-not-found",
    "gha-exit-code-1-eslint",
    "gha-timeout-job",
    "gha-yarn-frozen-lockfile",
    "gha-pnpm-frozen-lockfile",
    "gha-docker-buildx-not-setup",
    "gha-node-version-mismatch",
    "gha-missing-env-variable",
    "gha-port-already-in-use",
    "gha-checkout-lfs",
    "gha-terraform-state-lock",
    "gha-jest-cannot-find-module",
    "gha-aws-credentials-missing",
    "gha-playwright-browser-missing",
    "gha-cypress-video-artifact",
    "gha-python-version-mismatch",
    "gha-docker-compose-version",
    "gha-gradle-oom",
    "gha-maven-dependency-resolve",
    "gitlab-pipeline-stuck-pending",
    "gha-ssh-key-permission-denied",
    "gha-codecov-upload-fail",
    "gha-kubernetes-kubectl-auth",
    "gha-ruby-bundler-fail",
    "gha-go-module-private",
    "gha-cache-restore-fail",
    "gha-sonarqube-quality-gate",
    "gha-gh-pages-deploy-fail",
    "gha-trivy-scan-fail",
    "gha-matrix-strategy-fail-fast",
    "gha-permissions-denied-chmod",
    "gha-vercel-deploy-fail",
  ];

  return [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 1,
    },
    ...failures.map((id) => ({
      url: `${baseUrl}/errors/${id}`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    })),
  ];
}